-- MySQL Script generated by MySQL Workbench
-- Wed Jul 16 11:34:12 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema librarymanagement
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema librarymanagement
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `librarymanagement` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `librarymanagement` ;

-- -----------------------------------------------------
-- Table `librarymanagement`.`author_book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `librarymanagement`.`author_book` (
  `author_id` INT NOT NULL,
  `book_id` INT NOT NULL,
  PRIMARY KEY (`author_id`, `book_id`),
  INDEX `book_id` (`book_id` ASC) VISIBLE,
  CONSTRAINT `author_book_ibfk_1`
    FOREIGN KEY (`author_id`)
    REFERENCES `librarymanagement`.`authors` (`author_id`)
    ON DELETE CASCADE,
  CONSTRAINT `author_book_ibfk_2`
    FOREIGN KEY (`book_id`)
    REFERENCES `librarymanagement`.`books` (`book_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `librarymanagement`.`authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `librarymanagement`.`authors` (
  `author_id` INT NOT NULL AUTO_INCREMENT,
  `author_name` VARCHAR(255) NOT NULL,
  `author_dob` DATE NULL DEFAULT NULL,
  `author_dod` DATE NULL DEFAULT NULL,
  `biography` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`author_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `librarymanagement`.`book_genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `librarymanagement`.`book_genre` (
  `book_id` INT NOT NULL,
  `genre_id` INT NOT NULL,
  PRIMARY KEY (`book_id`, `genre_id`),
  INDEX `genre_id` (`genre_id` ASC) VISIBLE,
  CONSTRAINT `book_genre_ibfk_1`
    FOREIGN KEY (`book_id`)
    REFERENCES `librarymanagement`.`books` (`book_id`)
    ON DELETE CASCADE,
  CONSTRAINT `book_genre_ibfk_2`
    FOREIGN KEY (`genre_id`)
    REFERENCES `librarymanagement`.`genres` (`genre_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `librarymanagement`.`book_instances`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `librarymanagement`.`book_instances` (
  `book_instance_id` INT NOT NULL AUTO_INCREMENT,
  `book_id` INT NOT NULL,
  `acquired_date` DATE NOT NULL,
  `status` VARCHAR(50) NOT NULL DEFAULT 'available',
  `note` TEXT NOT NULL,
  PRIMARY KEY (`book_instance_id`),
  INDEX `book_id` (`book_id` ASC) VISIBLE,
  CONSTRAINT `book_instances_ibfk_1`
    FOREIGN KEY (`book_id`)
    REFERENCES `librarymanagement`.`books` (`book_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `librarymanagement`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `librarymanagement`.`books` (
  `book_id` INT NOT NULL AUTO_INCREMENT,
  `book_name` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  `page_number` INT NOT NULL,
  `url_image` VARCHAR(255) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`book_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `librarymanagement`.`borrowing_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `librarymanagement`.`borrowing_details` (
  `borrowing_receipt_id` INT NOT NULL,
  `book_instance_id` INT NULL,
  PRIMARY KEY (`borrowing_receipt_id`, `book_instance_id`),
  INDEX `book_instance_id` (`book_instance_id` ASC) VISIBLE,
  CONSTRAINT `borrowing_details_ibfk_1`
    FOREIGN KEY (`borrowing_receipt_id`)
    REFERENCES `librarymanagement`.`borrowing_receipts` (`borrowing_receipt_id`)
    ON DELETE CASCADE,
  CONSTRAINT `borrowing_details_ibfk_2`
    FOREIGN KEY (`book_instance_id`)
    REFERENCES `librarymanagement`.`book_instances` (`book_instance_id`)
    ON DELETE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `librarymanagement`.`borrowing_receipts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `librarymanagement`.`borrowing_receipts` (
  `borrowing_receipt_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `borrowed_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `due_date` DATETIME NOT NULL,
  `actual_return_date` DATETIME NULL,
  `status` VARCHAR(50) NOT NULL DEFAULT 'active',
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`borrowing_receipt_id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `borrowing_receipts_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `librarymanagement`.`users` (`user_id`)
    ON DELETE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `librarymanagement`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `librarymanagement`.`comments` (
  `comment_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `book_id` INT NOT NULL,
  `content` TEXT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`comment_id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `book_id` (`book_id` ASC) VISIBLE,
  CONSTRAINT `comments_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `librarymanagement`.`users` (`user_id`)
    ON DELETE CASCADE,
  CONSTRAINT `comments_ibfk_2`
    FOREIGN KEY (`book_id`)
    REFERENCES `librarymanagement`.`books` (`book_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `librarymanagement`.`fines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `librarymanagement`.`fines` (
  `fine_id` INT NOT NULL AUTO_INCREMENT,
  `fine_type` VARCHAR(255) NOT NULL,
  `fee` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`fine_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `librarymanagement`.`follows`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `librarymanagement`.`follows` (
  `user_id` INT NOT NULL,
  `author_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `author_id`),
  INDEX `author_id` (`author_id` ASC) VISIBLE,
  CONSTRAINT `follows_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `librarymanagement`.`users` (`user_id`)
    ON DELETE CASCADE,
  CONSTRAINT `follows_ibfk_2`
    FOREIGN KEY (`author_id`)
    REFERENCES `librarymanagement`.`authors` (`author_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `librarymanagement`.`genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `librarymanagement`.`genres` (
  `genre_id` INT NOT NULL AUTO_INCREMENT,
  `genre_name` VARCHAR(100) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`genre_id`),
  UNIQUE INDEX `genre_name` (`genre_name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `librarymanagement`.`likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `librarymanagement`.`likes` (
  `user_id` INT NOT NULL,
  `book_id` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`, `book_id`),
  INDEX `book_id` (`book_id` ASC) VISIBLE,
  CONSTRAINT `likes_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `librarymanagement`.`users` (`user_id`)
    ON DELETE CASCADE,
  CONSTRAINT `likes_ibfk_2`
    FOREIGN KEY (`book_id`)
    REFERENCES `librarymanagement`.`books` (`book_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `librarymanagement`.`publisher_book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `librarymanagement`.`publisher_book` (
  `publisher_id` INT NOT NULL,
  `book_id` INT NOT NULL,
  `public_date` DATE NOT NULL,
  PRIMARY KEY (`publisher_id`, `book_id`),
  INDEX `book_id` (`book_id` ASC) VISIBLE,
  CONSTRAINT `publisher_book_ibfk_1`
    FOREIGN KEY (`publisher_id`)
    REFERENCES `librarymanagement`.`publishers` (`publisher_id`)
    ON DELETE CASCADE,
  CONSTRAINT `publisher_book_ibfk_2`
    FOREIGN KEY (`book_id`)
    REFERENCES `librarymanagement`.`books` (`book_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `librarymanagement`.`publishers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `librarymanagement`.`publishers` (
  `publisher_id` INT NOT NULL AUTO_INCREMENT,
  `publisher_name` VARCHAR(255) NOT NULL,
  `publisher_address` TEXT NOT NULL,
  `year_of_establish` INT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`publisher_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `librarymanagement`.`ratings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `librarymanagement`.`ratings` (
  `rating_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `book_id` INT NOT NULL,
  `rate` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`rating_id`),
  UNIQUE INDEX `user_id` (`user_id` ASC, `book_id` ASC) VISIBLE,
  INDEX `book_id` (`book_id` ASC) VISIBLE,
  CONSTRAINT `ratings_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `librarymanagement`.`users` (`user_id`)
    ON DELETE CASCADE,
  CONSTRAINT `ratings_ibfk_2`
    FOREIGN KEY (`book_id`)
    REFERENCES `librarymanagement`.`books` (`book_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `librarymanagement`.`receipt_fines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `librarymanagement`.`receipt_fines` (
  `receipt_fine_id` INT NOT NULL AUTO_INCREMENT,
  `borrowing_receipt_id` INT NOT NULL,
  `fine_id` INT NOT NULL,
  `amount` DECIMAL(10,2) NOT NULL,
  `book_status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`receipt_fine_id`),
  INDEX `borrowing_receipt_id` (`borrowing_receipt_id` ASC) VISIBLE,
  INDEX `fine_id` (`fine_id` ASC) VISIBLE,
  CONSTRAINT `receipt_fines_ibfk_1`
    FOREIGN KEY (`borrowing_receipt_id`)
    REFERENCES `librarymanagement`.`borrowing_receipts` (`borrowing_receipt_id`)
    ON DELETE CASCADE,
  CONSTRAINT `receipt_fines_ibfk_2`
    FOREIGN KEY (`fine_id`)
    REFERENCES `librarymanagement`.`fines` (`fine_id`)
    ON DELETE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `librarymanagement`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `librarymanagement`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `phone_number` VARCHAR(20) NULL DEFAULT NULL,
  `address` TEXT NULL DEFAULT NULL,
  `role` VARCHAR(50) NOT NULL DEFAULT 'member',
  `status` VARCHAR(50) NOT NULL DEFAULT 'active',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;